### ISSUE TITLE
监测不到签到

### ISSUE THREAD

**Issue by kuxiabk** [celesWuff/ktpwarp-server#1]
server正常启动，state也是online，courseId没有填错，web端也出现了正在进行的课程了，但通过自己创建的课程，测试发起签到，server无法监测到

**Comment by kuxiabk** [comment]
![image](https://user-images.githubusercontent.com/37491747/228939035-76a775ef-77d0-4c55-ac06-6a43bd776108.png)

**Comment by kuxiabk** [comment]
已解决，看了一下日志，应该是依赖问题，找不到structuredClone这个函数

**Comment by celesWuff** [comment]
很高兴得知您已经找到了问题的原因。structuredClone 函数在 Node.js 17 才被引入，因此将 Node.js 更新到 17 以上的版本即可，当然，我会建议使用 18 LTS 或更高版本。我稍后会更新代码以修复您遇到的问题。

此外，我想提醒您，请在将问题的细节共享给我们或其他人时，仔细检查并打码所有的关键参数，例如您的域名、API 路径和课程 ID 等，以保护您的隐私和安全。

**Comment by kuxiabk** [comment]
同学你好，我已收到你的邮件~（此为系统自动回复，您无需回复）来自酷侠之路
