### ISSUE TITLE
没有检测到课程

### ISSUE THREAD

**Issue by Mathew-Carl** [celesWuff/ktpwarp-server#10]
![196026c22bab052b9f5090665d6a5cf](https://github.com/celesWuff/ktpwarp-server/assets/150131584/cba1e141-1fbb-4bd9-bb3e-0afa9182718d)
![c59d702a47c56f7f6ed2083cbbd19aa](https://github.com/celesWuff/ktpwarp-server/assets/150131584/252c358e-866e-4d3d-b802-995f9a2203e9)
请问一下我已经在服务器部署好了,但在自己测试的时候发现签到中没有正在进行的课程,但我已经在代码里配置好了,并且我在本地电脑部署时可以检测到课程,请问是什么原因node版本,两个地方的软件版本和node版本都是一样的

**Comment by celesWuff** [comment]
可能是由于您的服务器系统时区不一致。

已发布 1.3.3-beta 版本，程序将会始终选定 `Asia/Shanghai` 时区。您可以更新至此版本，也可以仅调整服务器时区来使用上一个版本。

**Comment by Mathew-Carl** [comment]
好嘞，谢谢你的提示，我明白是哪里的问题啦

**Comment by Mathew-Carl** [comment]
> 好嘞，谢谢你的提示，我明白是哪里的问题啦

太谢谢了，我去改了下时区，果然是时区的问题，我想了一天也没找出来原因
