### ISSUE TITLE
无法连接到服务器

### ISSUE THREAD

**Issue by bytelazy** [celesWuff/ktpwarp-server#2]
os: win10专业版
node-version: 18
已执行操作：修改配置文件中`WEBSOCKET_SERVER_PATH`配置项，运行npm start成功
预期结果：在https://celeswuff.github.io/ktpwarp-web/通过 wss://127.0.0.1:11451/{$costomizePath}可以连接服务器
实际结果："连接失败，请检查服务器地址是否正确。"

请教是什么地方可能出现了问题？

**Comment by celesWuff** [comment]
您访问的是本地主机，推测您没有开启 TLS，因此您应该使用 `ws://` 而非 `wss://` 。

**Comment by bytelazy** [comment]
确实如您所说的一致，访问本地主机使用`ws://` 后可以正常连接
