### ISSUE TITLE
针对固定ip前缀可能出现的问题

### ISSUE THREAD

**Issue by SetBoerk** [celesWuff/ktpwarp-server#3]
作者你好，我部署了你的ktpwarp项目，在实际应用中遇到了针对固定ip前缀教师点名的问题，我的解决方法是把FAKE_IP_PREFIX修改为一个数组，数组里用来放多个我的属地的ip前缀，在getAuthenticatedHeaders方法里面我修改为了随机在FAKE_IP_PREFIX数组里挑选一个做前缀，
`export function getAuthenticatedHeaders(credential: CredentialType): any {
  const headers = structuredClone(HEADERS);
  headers["token"] = credential.token;
  // 从 FAKE_IP_PREFIX_ARRAY 中随机选择一个前缀
  const randomPrefixIndex = Math.floor(Math.random() * FAKE_IP_PREFIX_ARRAY.length);
  const selectedPrefix = FAKE_IP_PREFIX[randomPrefixIndex];
  headers["X-Forwarded-For"] = selectedPrefix + fakeIpSuffix.next(); 
  return headers; 
}`

**Comment by GR666** [comment]
课堂派是不是更新了，二维码扫不上了，楼主还能用吗

**Comment by SetBoerk** [comment]
> 课堂派是不是更新了，二维码扫不上了，楼主还能用吗

大码可以，小码不行

**Comment by celesWuff** [comment]
感谢您的提议，1.3 版本实现了该功能。
