### ISSUE TITLE
部署程序后，创建的进程并不对设置的端口进行监听

### ISSUE THREAD

**Issue by rocco1226** [celesWuff/ktpwarp-server#5]
可以查看到进程，但是在netstat中没有进程在对config.ts中设置的端口号进行监听，也没有其他任何进程对该端口号监听，请问有人可以帮助我吗？

**Comment by rocco1226** [comment]
操作系统：win10
node version：v20.10.0
在同一网络进行测试，ip地址无误，防火墙未屏蔽此端口
![屏幕截图 2024-02-24 184259](https://github.com/celesWuff/ktpwarp-server/assets/155219758/d9eaef06-7484-409a-8184-723aba44a412)
![屏幕截图 2024-02-24 184323](https://github.com/celesWuff/ktpwarp-server/assets/155219758/28597d63-da6c-4e48-836f-31a02250b5f4)
![屏幕截图 2024-02-24 184352](https://github.com/celesWuff/ktpwarp-server/assets/155219758/06c64ad2-17e1-4203-a577-2dafa439634e)
![Screenshot_2024-02-24-18-45-59-465_io.github.celeswuff.ktpwarp.jpg](https://github.com/celesWuff/ktpwarp-server/assets/155219758/7608207b-1d45-4e97-9a10-1cf0e1e7b9fe)

![Screenshot_2024-02-24-18-46-16-010_io.github.celeswuff.ktpwarp.jpg](https://github.com/celesWuff/ktpwarp-server/assets/155219758/c76cd1da-12a2-4c81-8455-70c721600d73)

**Comment by celesWuff** [comment]
可能是程序没有正常启动，可以使用 `pnpm dev` 命令查看启动时的日志来确定问题原因。

**Comment by rocco1226** [comment]
> 可能是程序没有正常启动，可以使用 `pnpm dev` 命令查看启动时的日志来确定问题原因。

非常感谢！经过测试，目前已解决问题
![Uploading 屏幕截图 2024-03-12 160710.png…]()
