### ISSUE TITLE
fakeip无效？无论怎样设置教师端都显示签到ip为0.0.0.0

### ISSUE THREAD

**Issue by Pinirva** [celesWuff/ktpwarp-server#8]
![04a51c82690041048473124fa76d9bec](https://github.com/celesWuff/ktpwarp-server/assets/53863654/ebe6656c-bd56-4d3e-9cfb-07a6ef1ab1cb)

**Comment by Pinirva** [comment]
问题我已修复，似乎多ip功能并不完善，将fakeip改为之前版本的单个 export const FAKE_IP_PREFIX = "58.32.12."; 这样即可使用，望知悉
![5ff863332b58746cfb18a8a3276c3f5a](https://github.com/celesWuff/ktpwarp-server/assets/53863654/f0e87990-aa07-4e9f-9778-530cb23ff57c)

**Comment by celesWuff** [comment]
已在 1.3.1 中修复，感谢您的报告。
