### ISSUE TITLE
Retrying fetch... (1/3), error: CERT_HAS_EXPIRED

### ISSUE THREAD

**Issue by Pinirva** [celesWuff/ktpwarp-server#9]
突然就变这样了，到底是什么证书过期了呢，服务端wss的证书正常，pnpm源也正常
![43adc1f06cefd6bc9634041ef5fc912c](https://github.com/celesWuff/ktpwarp-server/assets/53863654/9fdfb285-8d60-4e33-b4d1-1ab01ac97ea3)

**Comment by Pinirva** [comment]
我想我找到原因了，openapiv100.ketangpai.com的证书刚好今天过期了...
![00a2bd771d905c35c9924fec9f9ca9d2](https://github.com/celesWuff/ktpwarp-server/assets/53863654/7ba27ee1-cd04-42fd-9671-f73baf4bbc46)

**Comment by Zeroization** [comment]
> 我想我找到原因了，openapiv100.ketangpai.com的证书刚好今天过期了... ![00a2bd771d905c35c9924fec9f9ca9d2](https://private-user-images.githubusercontent.com/53863654/320486560-7ba27ee1-cd04-42fd-9671-f73baf4bbc46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1OTE3NTUsIm5iZiI6MTcxMjU5MTQ1NSwicGF0aCI6Ii81Mzg2MzY1NC8zMjA0ODY1NjAtN2JhMjdlZTEtY2QwNC00MmZkLTk2NzEtZjczYmFmNGJiYzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDE1NTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NzNlYzMwMGY2NzRjNzRiNTIwOTYxOGU3ODFiYjkxM2ViNmRhNGE5ODI4NzIzMzFlM2QzMDM4ZGE4MTIzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.drmoYi-sxc4g6YrJeA9Z5YnhBiQxn1NIH3u05i-fKEs)

对，你可以把 `.ts` 代码中的`"https://open...."`改成`http://open.....`。或者等人家更新证书

**Comment by celesWuff** [comment]
气笑了，而且这个问题还不好解决。

背景：
`openapiv100` 原本是 PC 版使用的后端，支持 http2。
移动端（微信公众号）使用的是 `openapiv5`，至今仍然只有 http1.1。
在 http2 多路复用的支持下，`openapiv100` 的效率远超 `openapiv5`：在海外部署时，若不使用 `openapiv100` 则二维码签到超时概率剧增。

现在，似乎 PC 版反向升级，重新使用了 `openapiv5`，丧失了 http2 的能力。
不排除 `openapiv100` 可能已被放弃。

为保证基本的正常使用，1.3.2-beta 版本已经回退至 `openapiv5`。

**目前，如果仍然需要使用 http2，最简单的一种临时解决方法是在系统 hosts 中加入以下内容：**
```
118.31.55.247 openapiv5.ketangpai.com
```
这会为 `openapiv5` 的域名使用原来 `openapiv100` 支持 http2 的服务端，但该方法很可能在未来失效。
我们会持续关注此问题。

**Comment by celesWuff** [comment]
补充：

可以将 `https://openapiv100...` 改为 `http://openapiv100...` 吗？

可以，但不建议。互联网上的一切流量都应该加密。ktpWarp 能够正确地保持连接，以免除 TLS 加密握手带来的延迟；http2 不会在非加密连接上运作，因缺少多路复用，选择不加密反而可能导致签到的延迟增加。

**Comment by Pinirva** [comment]
现在 https://openapiv100.ketangpai.com/ 证书已经恢复了 大佬

**Comment by celesWuff** [comment]
草

**Comment by celesWuff** [comment]
1.3.2-beta 更新已撤回，尽管如此，PC 版不再使用 `openapiv100` 的改动仍然值得关注。
